# Generated by Django 6.0.7 on 2026-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_slug_product_slug_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
